sudo: false
language: node_js
node_js:
- '7'
deploy:
  provider: npm
  email: roger@zooniverse.org
  api_key: $NPM_API_KEY
  on:
    tags: true
env:
  global:
    secure: KIUvvcY8wAMjazGvBCI8Qlq2iGa516LQeV2x0Z04vwJ3RrZmijf6xEeIxZjxrOAMPGPqRYDPXMDwdIKz1uDIRH3sguQsF82g3Qb8t/NlLFP1jPev+MHsFuC1OaqDwZm8lyMGrMR8b3jSCwnOIiatqClZ0Jp+vUgE0rHuBZAMGUHUh16TlZ5Ji0oflFlFO8F0eJH7RcW8EGF273XsDLsIHpuiu1Q2CqyApULfGD9//t/PzNqIslulNAmnD6xsPDjQRHSevXezTicx4mfnwurMR9BHEhXh0VBjtx2zpmmRWBZqivn57Mkf7MHkiPtW4xmwyLljWJnNaNoCMjFZCn19NADgsLYTPRoWvFaLHomGuKGr937znxA4sNqCYPD5k0XP9WY7Aa5NfDIyoKq1SmcoMKO+N4MK4Lcb2TJvdvILPXuWFhlyXjfA0MQ/0NBAA1EiV7eJyNFRiKv+N3BvOHGjsscxuCWikOQ/IB98AsuZMgklWA4oJldWXaOKuZ3lict3geOGdUw6/nL/gusdjE0qJJ3ddbNZITDkw3ujWlruACY3pxDNr2N7XB1uDlljLO/CRzMn5OVLnHaXmG7Pc8xNOXJixUaazs4kkF//OHBV9LMoxfMFgDOk8ee2lToQ4RSsM460gncdLvK6w7zi37FqkmKXwUK83yqboGxryJGcv3s=
