sudo: false
language: node_js
node_js:
  - '7'

deploy:
  provider: npm
  email: roger@zooniverse.org
  api_key: $NPM_API_TOKEN
  on:
    tags: true

env:
  secure: "sUKRn7VYLggbDT45wXkTuCZTjNqyyteOwULZFH34g6qqKjbQ+Xmrd1c9ubnlGpJcWf0RbSjthZObCz9KbL8kZ149KmLTaGD670nkgVe623j1YFU3HRzjFjwiWRw3j8hI6g9YpBhSJhRsq/TbsVLvai8jO8x04TvbU+bTvGqvbprDhGsZz/lmjp6k1O0RjLPjb1doYt2Sz8LA4rgCFMl885ygA1n4dVck/3wl1bbmydJQg0UPs7qz0Z2Dvw1Nm6Vv/epmkOe2qGH1NPm/TZM6E0jTqHEjmgIV5JqnZqX6TyMyWhqqYuh6uT7P8573prfbvAzqt8G4ldBW8db9IcLMbYjYd77wI80al0zXxdDBOACLzUSH/1c9UhzG+NOAjcywu72IKCysbHp5FnWHxlGkQuEpklZxVcSp8JFKbWX4q5q/pzTWKNe2x15ZILCFmQ/BFy+BG731coIbUaeaxacH7hhKbauA6tssfJ6WL4/f+vUtZpgWTUhYbIx0qU2IIErUUM+tT5z6orr43I54l7pfyjQIfRUD+uInadEjSW3aGjZ5S1r/lSDAa+H/ZHWCCVJAi+vqoaKTmPWDy3xwRP4r3mCoaWsguJNo8ckgdUA9xJRUKRiZqFLuHw/Lem6G1Hgw4Em3ngeWA7foZdtbTS74W8zJySw3pV+sIDTVQ/QUABU="
